name: Build and Sync LaTeX PDF

on:
  push:
    branches: [ main ]
    paths:
      - '**.tex'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ctufit-thesis.tex
          compiler: xelatex

      - name: Commit and push if PDF changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Check if the PDF has changed compared to the repo version
          if [ -n "$(git status --porcelain ctufit-thesis.pdf)" ]; then
            git add main.pdf
            git commit -m "Auto-update compiled PDF [skip ci]"
            git push
          else
            echo "No changes detected in PDF. Skipping commit."
          fi